import { dirname, join } from "@std/path";
import { ensureDir } from "@std/fs/ensure-dir";

const SRC_PATH = "src/swisseph/swephexp.h";
const OUT_PATH = "src/swisseph_api.generated.ts";
const EXPORTS_PATH = "bindings/exported_functions.json";

async function generate() {
  const content = await Deno.readTextFile(SRC_PATH);

  const defineRegex = /#\s*define\s+(\w+)\s+(.+)/g;
  const extDefRegex = /ext_def\s*\(\s*([^)]+)\s*\)\s*(\w+)\s*\(([^;]+)\)\s*;/g;

  const constants: Record<string, string> = {};
  const functions: Array<{
    returnType: string;
    name: string;
    args: Array<{ type: string; name: string }>;
  }> = [];

  // Parse Constants
  let match;
  while ((match = defineRegex.exec(content)) !== null) {
    const key = match[1];
    let value = match[2].trim();

    const commentStart = value.indexOf("/*");
    if (commentStart !== -1) {
      const quoteCount =
        (value.substring(0, commentStart).match(/"/g) || []).length;
      if (quoteCount % 2 === 0) {
        value = value.substring(0, commentStart).trim();
      }
    }
    const lineComment = value.indexOf("//");
    if (lineComment !== -1) {
      const quoteCount =
        (value.substring(0, lineComment).match(/"/g) || []).length;
      if (quoteCount % 2 === 0) {
        value = value.substring(0, lineComment).trim();
      }
    }

    constants[key] = value;
  }

  // Parse Functions
  while ((match = extDefRegex.exec(content)) !== null) {
    const returnType = match[1].trim();
    const name = match[2].trim();
    const argsRaw = match[3].trim();

    const args = argsRaw.split(",").map((arg) => {
      arg = arg.trim();
      const lastSpace = arg.lastIndexOf(" ");
      if (lastSpace === -1) return { type: arg, name: "" };
      let type = arg.substring(0, lastSpace).replace(/\*/g, "").trim();
      if (arg.includes("*")) type += "*";

      let paramName = arg.substring(lastSpace + 1).replace(/\*/g, "").trim();

      if (paramName.includes("[")) {
        paramName = paramName.split("[")[0];
        type += "[]";
      }
      return { type, name: paramName };
    });

    functions.push({ returnType, name, args });
  }

  // Generate TypeScript
  const lines: string[] = [];
  lines.push(`// Auto-generated by scripts/codegen.ts`);
  lines.push(`// Do not edit manually.\n`);

  lines.push(`export const Constants = {`);
  for (const [k, v] of Object.entries(constants)) {
    if (k.includes("(")) continue;
    if (!isNaN(parseFloat(v)) || v.startsWith("0x")) {
      lines.push(`  ${k}: ${v},`);
    } else if (v.startsWith('"')) {
      lines.push(`  ${k}: ${v},`);
    }
  }
  lines.push(`} as const;\n`);

  lines.push(`export interface SwissEphExports extends WebAssembly.Exports {`);
  for (const func of functions) {
    const tsArgs = func.args.map((arg, idx) => {
      const name = arg.name || `arg${idx}`;
      return `${name}: number`;
    }).join(", ");

    let tsRet = "number";
    if (func.returnType === "void") tsRet = "void";

    lines.push(`  ${func.name}(${tsArgs}): ${tsRet};`);
  }
  // Add mandatory runtime exports
  lines.push(`  malloc(size: number): number;`);
  lines.push(`  free(ptr: number): void;`);
  lines.push(`}\n`);

  lines.push(
    `export const Signatures = ${JSON.stringify(functions, null, 2)};`,
  );

  await Deno.writeFile(OUT_PATH, new TextEncoder().encode(lines.join("\n")));
  console.log(`Generated ${OUT_PATH}`);

  // Generate Compiler Export List (JSON)
  const exportNames = functions.map((f) => f.name);
  exportNames.push("malloc", "free");

  await ensureDir(dirname(EXPORTS_PATH));
  await Deno.writeTextFile(EXPORTS_PATH, JSON.stringify(exportNames, null, 2));
  console.log(`Generated ${EXPORTS_PATH}`);
}

if (import.meta.main) {
  await generate();
}
