import { dirname, join } from "@std/path";
import { ensureDir } from "@std/fs/ensure-dir";
import { parseMetadata } from "./metadata.ts";

const SRC_PATH = "vendor/swisseph/swephexp.h";
const DEF_PATH = "vendor/swisseph/sweodef.h";
const OUT_PATH = "generated/swisseph_api.generated.ts";
// Removed redundant EXPORTS_PATH and WRAPPERS_PATH unused variables if not needed,
// OR update them if you want to keep them for debug:
const EXPORTS_PATH = "generated/exported_functions.json";
// const WRAPPERS_PATH = "bindings/generated_wrappers.ts"; // Removing this

async function generate() {
  const { constants, functions } = await parseMetadata(SRC_PATH, DEF_PATH);

  // Generate TypeScript
  const lines: string[] = [];
  lines.push(`// Auto-generated by scripts/codegen.ts`);
  lines.push(`// Do not edit manually.\n`);

  lines.push(`export const Constants = {`);
  for (const [k, v] of Object.entries(constants)) {
    if (k.includes("(")) continue;

    // Skip if value contains identifier characters (letters) that aren't hex
    // Check for letters a-z, A-Z.
    // Allow 'x' if preceded by '0' (hex coverage is approximate but practically works for 0x...)
    // Actually, safer: allow only digits, whitespace, operators, parents, and 0x hex.

    // Check if it looks like a hex number
    const isHex = /^0x[0-9a-fA-F]+$/.test(v);

    // Check if it contains letters (and is not hex)
    if (!isHex && /[a-zA-Z]/.test(v)) {
      // Allow scientific notation e.g. 1E-10
      if (!/^-?[\d.]+[eE][+-]?\d+$/.test(v)) {
        continue; // Skip values with identifiers like DEG, SEFLG_..., etc.
      }
    }

    let cleanValue = v;
    // Fix octal: if it starts with 0 and has digits, and isn't 0x or just 0/0.
    if (
      /^0\d+/.test(cleanValue) && !cleanValue.startsWith("0x") &&
      !cleanValue.includes(".")
    ) {
      cleanValue = cleanValue.replace(/^0/, "0o");
    }

    if (!cleanValue) continue;

    // Attempt to validate if it's a valid expression we can output
    // We strictly output if it parses visually as number or math
    lines.push(`  ${k}: ${cleanValue},`);
  }
  lines.push(`} as const;\n`);

  lines.push(`export interface SwissEphExports extends WebAssembly.Exports {`);
  for (const func of functions) {
    const tsArgs = func.args.map((arg, idx) => {
      const name = arg.name || `arg${idx}`;
      return `${name}: number`;
    }).join(", ");

    let tsRet = "number";
    if (func.returnType === "void") tsRet = "void";

    lines.push(`  ${func.name}(${tsArgs}): ${tsRet};`);
  }
  // Add mandatory runtime exports
  lines.push(`  malloc(size: number): number;`);
  lines.push(`  free(ptr: number): void;`);
  lines.push(`}\n`);

  lines.push(
    `export const Signatures = ${JSON.stringify(functions, null, 2)};`,
  );

  await Deno.writeFile(OUT_PATH, new TextEncoder().encode(lines.join("\n")));
  console.log(`Generated ${OUT_PATH}`);

  // Generate Compiler Export List (JSON)
  const exportNames = functions.map((f) => f.name);
  exportNames.push("malloc", "free");

  await ensureDir(dirname(EXPORTS_PATH));
  await Deno.writeTextFile(EXPORTS_PATH, JSON.stringify(exportNames, null, 2));
  console.log(`Generated ${EXPORTS_PATH}`);
}

if (import.meta.main) {
  await generate();
}
