/**
 * Enhanced Swetest - Full Precision Golden Value Generator
 * 
 * This tool links against the Swiss Ephemeris library and outputs
 * planetary positions with full IEEE 754 double precision (~17 digits).
 * 
 * It does NOT modify the submodule but uses it as a library dependency.
 * 
 * Compile: clang -o swetest_enhanced swetest_enhanced.c -I../src/swisseph -L../src/swisseph -lswe -lm
 * Run: DYLD_LIBRARY_PATH=../src/swisseph ./swetest_enhanced > ../tests/fixtures/golden_values_generated.ts
 */

#include <stdio.h>
#include <stdlib.h>
#include "swephexp.h"

/* ============================================================================
 * TEST CONFIGURATION - Modify these to expand test coverage
 * ============================================================================ */

/* Test dates covering different epochs */
typedef struct {
    double jd;
    const char *desc;
    const char *name;
} TestDate;

static TestDate test_dates[] = {
    { 2451545.0,   "J2000.0 Epoch (2000-01-01 12:00 TT)", "J2000" },
    { 2461054.5,   "2026-01-14 00:00:00 TT (Primary)", "PRIMARY" },
    { 2415020.5,   "1900-01-01 00:00:00 TT (Historical)", "HISTORICAL_1900" },
    { 2488069.5,   "2100-01-01 00:00:00 TT (Future)", "FUTURE_2100" },
    { 2436116.5,   "1957-10-04 (Sputnik)", "SPUTNIK" },
    { 2440587.5,   "1969-07-20 (Moon Landing)", "MOON_LANDING" },
};
static int num_dates = sizeof(test_dates) / sizeof(test_dates[0]);

/* Test locations */
typedef struct {
    double lat, lon, alt;
    const char *name;
} TestLocation;

static TestLocation test_locations[] = {
    { 47.3769, 8.5417, 0, "Zurich" },
    { 51.5074, -0.1278, 0, "London" },
    { 40.7128, -74.0060, 0, "NewYork" },
    { 35.6762, 139.6503, 0, "Tokyo" },
    { -33.8688, 151.2093, 0, "Sydney" },
    { 0.0, 0.0, 0, "Equator" },
    { 89.0, 0.0, 0, "NearNorthPole" },
    { -89.0, 0.0, 0, "NearSouthPole" },
};
static int num_locations = sizeof(test_locations) / sizeof(test_locations[0]);

/* All planet IDs */
static int planets[] = {
    SE_SUN, SE_MOON, SE_MERCURY, SE_VENUS, SE_MARS,
    SE_JUPITER, SE_SATURN, SE_URANUS, SE_NEPTUNE, SE_PLUTO,
    SE_MEAN_NODE, SE_TRUE_NODE, SE_MEAN_APOG, SE_OSCU_APOG,
    SE_CHIRON, SE_PHOLUS, SE_CERES, SE_PALLAS, SE_JUNO, SE_VESTA
};
static const char *planet_keys[] = {
    "SE_SUN", "SE_MOON", "SE_MERCURY", "SE_VENUS", "SE_MARS",
    "SE_JUPITER", "SE_SATURN", "SE_URANUS", "SE_NEPTUNE", "SE_PLUTO",
    "SE_MEAN_NODE", "SE_TRUE_NODE", "SE_MEAN_APOG", "SE_OSCU_APOG",
    "SE_CHIRON", "SE_PHOLUS", "SE_CERES", "SE_PALLAS", "SE_JUNO", "SE_VESTA"
};
static const char *planet_names[] = {
    "Sun", "Moon", "Mercury", "Venus", "Mars",
    "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto",
    "MeanNode", "TrueNode", "MeanApogee", "OscuApogee",
    "Chiron", "Pholus", "Ceres", "Pallas", "Juno", "Vesta"
};
static int num_planets = sizeof(planets) / sizeof(planets[0]);

/* House systems */
static char house_systems[] = { 'P', 'K', 'C', 'R', 'W', 'E', 'O', 'M', 'A', 'T', 'B' };
static const char *house_names[] = {
    "Placidus", "Koch", "Campanus", "Regiomontanus", "WholeSign",
    "Equal_ASC", "Porphyry", "Morinus", "Equal_MC", "Topocentric", "Alcabitius"
};
static int num_houses = sizeof(house_systems) / sizeof(house_systems[0]);

/* Sidereal modes */
static int sidereal_modes[] = { 0, 1, 3, 4, 5, 27, 30 };
static const char *sidereal_names[] = {
    "FaganBradley", "Lahiri", "Raman", "Ushashashi", "Krishnamurti", "TrueCitra", "TruePushya"
};
static int num_sidereal = sizeof(sidereal_modes) / sizeof(sidereal_modes[0]);

/* ============================================================================
 * MAIN
 * ============================================================================ */

int main(int argc, char *argv[]) {
    double xx[6];
    char serr[256];
    int i, j, iflag, retval;
    double cusps[37], ascmc[10];
    double deltat, sidtime, ayanamsa;
    
    /* Set ephemeris path */
    swe_set_ephe_path("../vendor/swisseph/ephe");
    
    /* Standard flags */
    iflag = SEFLG_SWIEPH | SEFLG_TRUEPOS | SEFLG_NOABERR | SEFLG_NONUT;
    
    printf("/**\n");
    printf(" * Golden Values - Maximum Precision (IEEE 754 double)\n");
    printf(" * Generated by swetest_enhanced from native C library\n");
    printf(" * Swiss Ephemeris Version: %s\n", swe_version(serr));
    printf(" * Generated: %s\n", __DATE__);
    printf(" *\n");
    printf(" * Coverage:\n");
    printf(" *   - %d celestial bodies (planets, nodes, asteroids)\n", num_planets);
    printf(" *   - %d test dates across epochs\n", num_dates);
    printf(" *   - %d geographic locations\n", num_locations);
    printf(" *   - %d house systems\n", num_houses);
    printf(" *   - %d sidereal modes\n", num_sidereal);
    printf(" */\n\n");
    
    /* ========================================================================
     * TEST DATES
     * ======================================================================== */
    printf("/** Test dates covering different epochs */\n");
    printf("export const TEST_DATES = {\n");
    for (i = 0; i < num_dates; i++) {
        printf("  %s: { jd: %.17g, desc: \"%s\" },\n", 
               test_dates[i].name, test_dates[i].jd, test_dates[i].desc);
    }
    printf("} as const;\n\n");
    
    /* Convenience export for primary test date */
    printf("/** Primary test Julian Day */\n");
    printf("export const TEST_JD = TEST_DATES.PRIMARY.jd;\n\n");
    
    /* ========================================================================
     * TEST LOCATIONS
     * ======================================================================== */
    printf("/** Test locations covering different latitudes */\n");
    printf("export const TEST_LOCATIONS = {\n");
    for (i = 0; i < num_locations; i++) {
        printf("  %s: { lat: %.17g, lon: %.17g, alt: %.17g },\n",
               test_locations[i].name, test_locations[i].lat, 
               test_locations[i].lon, test_locations[i].alt);
    }
    printf("} as const;\n\n");
    
    printf("/** Primary test location */\n");
    printf("export const TEST_LOCATION = TEST_LOCATIONS.Zurich;\n\n");
    
    /* ========================================================================
     * PLANET POSITIONS (for primary date)
     * ======================================================================== */
    printf("/** Planet positions for primary date (TT, true pos, no aberr/nut) */\n");
    printf("export const PLANET_POSITIONS = {\n");
    for (i = 0; i < num_planets; i++) {
        retval = swe_calc(test_dates[1].jd, planets[i], iflag, xx, serr);
        if (retval < 0) {
            fprintf(stderr, "Error calculating %s: %s\n", planet_keys[i], serr);
            printf("  %s: { lon: 0, lat: 0, dist: 0, name: \"%s\", error: true },\n",
                   planet_keys[i], planet_names[i]);
            continue;
        }
        printf("  %s: { lon: %.17g, lat: %.17g, dist: %.17g, name: \"%s\" },\n",
               planet_keys[i], xx[0], xx[1], xx[2], planet_names[i]);
    }
    printf("} as const;\n\n");
    
    /* ========================================================================
     * MULTI-DATE POSITIONS (all planets, all dates)
     * ======================================================================== */
    printf("/** Planet positions across all test dates */\n");
    printf("export const POSITIONS_BY_DATE = {\n");
    for (j = 0; j < num_dates; j++) {
        printf("  %s: {\n", test_dates[j].name);
        for (i = 0; i < num_planets; i++) {
            retval = swe_calc(test_dates[j].jd, planets[i], iflag, xx, serr);
            if (retval >= 0) {
                printf("    %s: { lon: %.17g, lat: %.17g },\n",
                       planet_keys[i], xx[0], xx[1]);
            }
        }
        printf("  },\n");
    }
    printf("} as const;\n\n");
    
    /* ========================================================================
     * DELTA-T VALUES
     * ======================================================================== */
    printf("/** Delta-T values for all test dates */\n");
    printf("export const DELTA_T_VALUES = {\n");
    for (j = 0; j < num_dates; j++) {
        deltat = swe_deltat(test_dates[j].jd);
        printf("  %s: { days: %.17g, seconds: %.17g },\n",
               test_dates[j].name, deltat, deltat * 86400.0);
    }
    printf("} as const;\n\n");
    
    printf("/** Primary Delta-T */\n");
    printf("export const DELTA_T = DELTA_T_VALUES.PRIMARY;\n\n");
    
    /* ========================================================================
     * SIDEREAL TIME
     * ======================================================================== */
    printf("/** Sidereal time at Greenwich for all test dates */\n");
    printf("export const SIDEREAL_TIME_VALUES = {\n");
    for (j = 0; j < num_dates; j++) {
        deltat = swe_deltat(test_dates[j].jd);
        sidtime = swe_sidtime(test_dates[j].jd - deltat);
        printf("  %s: %.17g,\n", test_dates[j].name, sidtime);
    }
    printf("} as const;\n\n");
    
    /* ========================================================================
     * HOUSE CUSPS (primary date, primary location, all systems)
     * ======================================================================== */
    printf("/** House cusps for all systems (Zurich, primary date) */\n");
    printf("export const HOUSE_CUSPS = {\n");
    deltat = swe_deltat(test_dates[1].jd);
    for (i = 0; i < num_houses; i++) {
        swe_houses(test_dates[1].jd - deltat, test_locations[0].lat, 
                   test_locations[0].lon, house_systems[i], cusps, ascmc);
        printf("  %s: {\n", house_names[i]);
        printf("    cusps: [");
        for (j = 1; j <= 12; j++) {
            printf("%.17g%s", cusps[j], j < 12 ? ", " : "");
        }
        printf("],\n");
        printf("    asc: %.17g, mc: %.17g, armc: %.17g, vertex: %.17g,\n",
               ascmc[0], ascmc[1], ascmc[2], ascmc[3]);
        printf("  },\n");
    }
    printf("} as const;\n\n");
    
    /* ========================================================================
     * AYANAMSA VALUES
     * ======================================================================== */
    printf("/** Ayanamsa values for all sidereal modes (primary date) */\n");
    printf("export const AYANAMSA_VALUES = {\n");
    for (i = 0; i < num_sidereal; i++) {
        swe_set_sid_mode(sidereal_modes[i], 0, 0);
        retval = swe_get_ayanamsa_ex(test_dates[1].jd, SEFLG_SWIEPH, &ayanamsa, serr);
        printf("  %s: { id: %d, value: %.17g },\n",
               sidereal_names[i], sidereal_modes[i], ayanamsa);
    }
    printf("} as const;\n\n");
    
    /* Reset sidereal mode */
    swe_set_sid_mode(0, 0, 0);
    
    /* ========================================================================
     * HOUSE SYSTEMS & SIDEREAL MODES (metadata)
     * ======================================================================== */
    printf("/** House system definitions */\n");
    printf("export const HOUSE_SYSTEMS = [\n");
    for (i = 0; i < num_houses; i++) {
        printf("  { code: \"%c\", name: \"%s\" },\n", house_systems[i], house_names[i]);
    }
    printf("];\n\n");
    
    printf("/** Sidereal mode definitions */\n");
    printf("export const SIDEREAL_MODES = [\n");
    for (i = 0; i < num_sidereal; i++) {
        printf("  { id: %d, name: \"%s\" },\n", sidereal_modes[i], sidereal_names[i]);
    }
    printf("];\n\n");
    
    /* ========================================================================
     * TOLERANCES
     * ======================================================================== */
    printf("/** Precision tolerances for testing */\n");
    printf("export const TOLERANCES = {\n");
    printf("  /** Machine epsilon - theoretical limit */\n");
    printf("  IDENTICAL: Number.EPSILON,  // ~2.22e-16\n");
    printf("  /** Practical strictest tolerance (IEEE 754 rounding) */\n");
    printf("  STRICT: 1e-13,\n");
    printf("  /** High precision (11 decimal places) */\n");
    printf("  HIGH: 1e-11,\n");
    printf("  /** Standard precision */\n");
    printf("  STANDARD: 1e-8,\n");
    printf("  /** Moshier fallback mode */\n");
    printf("  MOSHIER_FALLBACK: 1e-5,\n");
    printf("} as const;\n\n");
    
    /* ========================================================================
     * EDGE CASES
     * ======================================================================== */
    printf("/** Edge case values for robustness testing */\n");
    printf("export const EDGE_CASES = {\n");
    
    /* Very old date */
    retval = swe_calc(1721423.5, SE_SUN, iflag | SEFLG_MOSEPH, xx, serr); /* 1 AD */
    printf("  ancientDate: { jd: 1721423.5, sun_lon: %.17g, desc: \"1 AD\" },\n", xx[0]);
    
    /* Far future */
    retval = swe_calc(2816787.5, SE_SUN, iflag | SEFLG_MOSEPH, xx, serr); /* 3000 AD */
    printf("  futureDate: { jd: 2816787.5, sun_lon: %.17g, desc: \"3000 AD\" },\n", xx[0]);
    
    /* Julian/Gregorian boundary */
    retval = swe_calc(2299160.5, SE_SUN, iflag, xx, serr); /* Oct 15, 1582 */
    printf("  gregorianStart: { jd: 2299160.5, sun_lon: %.17g, desc: \"Gregorian calendar start\" },\n", xx[0]);
    
    printf("} as const;\n");
    
    swe_close();
    return 0;
}
